dbDefaults = {
	profile = {
		all = false,
		arena = true,
		battleground = true,
		field = true,
		sapath = SA_LOCALEPATH[GetLocale()] or "Interface\\Addons\\SoundAlerter\\voice\\",
		auraApplied = false,
		auraRemoved = false,
		castStart = false,
		castSuccess = false,
		interrupt = false,
		interruptfriendly = true,
		stun = true,
		hexfriend = true,
		friendlydebuff = false,
		friendpoly = true,
		friendcyclone = true,
		enemyinrange = true,
		class = true,
		drinking = true,
		shadowmeld = true,
		trinket = true,
		myself = false,
		Blindfriend = true,
--Druid
		thorns = true,
		survivalInstincts = true,
		innervate = true,
		barkskin = true,
		naturesSwiftness = true,
		naturesGrasp = true,
		frenziedRegeneration = true,
		enrage = false,
		dash = false,
		starfall = true,
		sfalldown = true,
		berserk = true,
--Paladin
		auraMastery = true,
		avengingWrath = true,
		handOfProtection = true,
		handOfFreedom = true,
		divineShield = true,
		divineSacrifice = true,
		handofsacrifice = true,
		divineGuardian = true,
		divinePlea = true,
--Rogue
		shadowDance = true,
		coldBlood = false,
		sprint = true,
		cloakOfShadows = true,
		adrenalineRush = true,
		evasion = true,
		vanish = true,
		bladeflurry = false,
		stealth = true,
--Warrior
		deathWish = true,
		enragedRegeneration = true,
		shieldWall = true,
		berserkerRage = true,
		retaliation = true,
		spellReflection = true,
		sweepingStrikes = true,
		bladestorm = true,
		lastStand = false,
		shieldWallDown = true,
--Priest
		painSuppression = true,
		powerInfusion = true,
		fearWard = true,
		dispersion = true,
		innerfocus = false,
		icyveins = false,
		desperatePrayer = true,
		divineHymn = true,

		waterShield = false,
		shamanisticRage = true,
		earthShield = true,
		naturesSwiftness2 = false,
		ElementalMastery = false,
--Mage
		iceBlock = true,
		arcanePower = false,
		invisibility = true,
--Death Knight
		iceboundFortitude = true,
		lichborne = true,
		vampiricBlood = false,
		antimagicshell = true,
		boneshield = false,
		hysteria = false,
		markofblood = true,
--Hunter
		theBeastWithin = true,
		deterrence = true,
		deterdown = true,
		readiness = true,

--SPELL_AURA_REMOVED
		protectionDown = true,
		bubbleDown = true,
		cloakDown = true,
		evasionDown = true,
		PSDown = true,
		dispersionDown = true,
		iceBlockDown = true,
		lichborneDown = false,
		iceboundFortitudeDown = false,
--General Heals
		bigHeal = true,
		resurrection = true,
--Races
		willoftheforsaken = false,
		Shadowmeld = false,
		giftofthenaaru = false,
		BloodFury = false,
		berserking = false,
		stoneform = false,
--Druid
		hibernate = true,
		cyclone = true,
--Priest
		manaBurn = true,
		shackleUndead = true,
		mindControl = true,
--Shaman
		hex = true,
		earthbind = false,
--Mage
		polymorph = true,
		evocation = true,
		HotStreak = false,
--Hunter
		revivePet = true,
		scareBeast = true,
--Warlock
		fear = true,
		fear2 = true,
		banish = true,
		deathcoil = true,
		shadowtrance = false,

--Druid
		skullBash = false,
--Paladin
		repentance = false,
		hammerofjustice = true,
--Rogue
		disarm2 = true,
		blind = true,
		kick = true,
		preparation = true,
--Warrior
		disarm = true,
		fear3 = true,
		pummel = true,
		shieldBash = true,
--Priest
		fear4 = true,
		shadowFiend = true,
		disarm3 = true,
--Shaman
		grounding = true,
		manaTide = true,
		tremorTotem = true,
--Mage
		coldSnap = true,
		deepFreeze = true,
		counterspell = true,
--Death Knight
		mindFreeze = true,
		strangulate = true,
		runeWeapon = true,
		gargoyle = true,
		hungeringCold = true,
--Hunter
		wyvernSting = true,
		silencingshot = true,
		aimedshot = true,
		freezingtrap = true,
--Warlock
		spellLock = true,
		demonicCircleTeleport = true,

		lockout = true,
--Chat Alerts
		bubblealert = true,
		stealthalert = true,
		vanishalert = true,
		trinketalert = false,
		interruptalert = true,
		party = false,
		say = false,
		clientonly = true,
		bgchat = false,
		blindonenemychat = true,
		blindonselfchat = true,
		InterruptText = "INTERRUPTED:",
		spelltext = "Casted",

	}
}